{
 "title": "RSSAnt-Actor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "op_type",
    "query": "inbox,execute,outbox,export,acked,done"
   },
   {
    "name": "job",
    "query": "label_values(actor_executor_time_bucket, job)"
   },
   { "name": "interval", "label": "Interval", "query": "10s,1m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Inbox Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(actor_queue_inbox_size{job=\"$job\"}[$interval])",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "Outbox Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(actor_queue_outbox_size{job=\"$job\"}[$interval])",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "Execute Time - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(actor_executor_time_bucket{job=\"$job\"}[$interval]))",
     "legendFormat": "{{dst}}"
    }
   ]
  },
  {
   "title": "Op_$op_type Rate / 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "repeat": "op_type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(actor_queue_op_total{op=\"$op_type\", job=\"$job\"}[$interval]) * 60) by (dst)",
     "legendFormat": "{{dst}}"
    }
   ]
  }
 ]
}