{
 "title": "RSSAnt-Actor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "op_type",
    "query": "inbox,execute,outbox,export,acked,done"
   },
   {
    "name": "job",
    "query": "label_values(actor_executor_time_bucket, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Inbox Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "actor_queue_inbox_size{job=\"$job\", dst!~\"actor.*\"}",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "Outbox Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "actor_queue_outbox_size{job=\"$job\", dst!~\"actor.*\"}",
     "legendFormat": "{{ dst }}"
    }
   ]
  },
  {
   "title": "Execute Time - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(actor_executor_time_bucket{job=\"$job\", dst!~\"actor.*\"}[1m]))",
     "legendFormat": "{{dst}}"
    }
   ]
  },
  {
   "title": "Op_$op_type Rate / 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "repeat": "op_type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(actor_queue_op_total{op=\"$op_type\", job=\"$job\", dst!~\"actor.*\"}[1m]) * 60) by (dst)",
     "legendFormat": "{{dst}}"
    }
   ]
  }
 ]
}