{
 "title": "RSSAnt-API",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Status Count / 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(rssant_api_time_count{path!~\"(admin/metrics|changelog\\\\.atom)\"}[60m]) * 3600) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "API Count / 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(rssant_api_time_count{path!=\"admin/metrics\"}[60m]) * 3600) by (path, method))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "API Latency P90 / 1h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(rssant_api_time_bucket{status=~\"^(2|3)\\\\d+\"}[60m])) by (le, method, path))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  }
 ]
}