# Generated by Django 2.1.7 on 2019-02-16 07:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='HTTP response headers, JSON object', null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('updating', 'updating'), ('ready', 'ready'), ('error', 'error')], default='pending', help_text='状态', max_length=20),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
