# Generated by Django 2.1.7 on 2019-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0002_auto_20190216_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='author',
            field=models.CharField(blank=True, help_text='作者', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(blank=True, help_text='描述或小标题', null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='encoding',
            field=models.CharField(blank=True, help_text='编码', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='etag',
            field=models.CharField(blank=True, help_text='HTTP response header ETag', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='icon',
            field=models.URLField(blank=True, help_text='网站Logo或图标', null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='last_modified',
            field=models.CharField(blank=True, help_text='HTTP response header Last-Modified', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='link',
            field=models.URLField(blank=True, help_text='网站链接', null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(blank=True, help_text='标题', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='version',
            field=models.CharField(blank=True, help_text='供稿格式/RSS/Atom', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='content',
            field=models.TextField(blank=True, help_text='文章内容', null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='dt_published',
            field=models.DateTimeField(blank=True, help_text='发布时间', null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='dt_updated',
            field=models.DateTimeField(blank=True, help_text='更新时间', null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='link',
            field=models.URLField(blank=True, help_text='文章链接', null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='summary',
            field=models.TextField(blank=True, help_text='摘要或较短的内容', null=True),
        ),
        migrations.AlterField(
            model_name='rssstory',
            name='title',
            field=models.CharField(blank=True, help_text='标题', max_length=200, null=True),
        ),
    ]
