# Generated by Django 2.1.7 on 2019-03-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0003_auto_20190327_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfeed',
            name='is_gzipped',
            field=models.BooleanField(blank=True, default=False, help_text='is content gzip compressed', null=True),
        ),
    ]
