# Generated by Django 2.1.7 on 2019-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0004_rawfeed_is_gzipped'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='rssant_api__feed_id_ed929c_idx',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='dt_readed',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='feed',
            name='total_storys',
            field=models.IntegerField(blank=True, default=0, help_text='Total storys', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='offset',
            field=models.IntegerField(default=-1, help_text='Story在Feed中的位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeed',
            name='dt_updated',
            field=models.DateTimeField(blank=True, help_text='更新时间', null=True),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='story_offset',
            field=models.IntegerField(blank=True, default=0, help_text='story offset', null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='dt_watched',
            field=models.DateTimeField(blank=True, help_text='关注时间', null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('feed', 'unique_id'), ('feed', 'offset')},
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['feed', 'offset'], name='rssant_api__feed_id_d6624c_idx'),
        ),
    ]
