# Generated by Django 2.1.7 on 2019-04-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0005_auto_20190416_1616'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userstory',
            name='rssant_api__user_id_c419be_idx',
        ),
        migrations.AddField(
            model_name='userstory',
            name='offset',
            field=models.IntegerField(default=-1, help_text='Story在Feed中的位置'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['user_feed', 'offset'], name='rssant_api__user_fe_cfb4de_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['user', 'story'], name='rssant_api__user_id_3bc826_idx'),
        ),
    ]
