# Generated by Django 2.1.7 on 2019-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0007_userfeed_is_from_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='dt_early_story_published',
            field=models.DateTimeField(blank=True, help_text='最老或18个月前发布的story的发布时间', null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='dt_latest_story_published',
            field=models.DateTimeField(blank=True, help_text='最新的story发布时间', null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='offset_early_story',
            field=models.IntegerField(blank=True, help_text='最老或18个月前发布的story的offset', null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='story_publish_period',
            field=models.IntegerField(blank=True, default=30, help_text='story发布周期(天)，按18个月时间窗口计算', null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='total_storys',
            field=models.IntegerField(blank=True, default=0, help_text='Number of total storys', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='dt_published',
            field=models.DateTimeField(help_text='发布时间'),
        ),
        migrations.AlterField(
            model_name='story',
            name='link',
            field=models.TextField(help_text='文章链接'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(help_text='标题', max_length=200),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['feed', 'dt_published'], name='rssant_api__feed_id_1bed8a_idx'),
        ),
    ]
