# Generated by Django 2.1.7 on 2019-07-14 05:50

from django.db import migrations, models
import jsonfield.fields
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0010_auto_20190519_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('registery_node', models.CharField(help_text='registery node name', max_length=200, unique=True)),
                ('registery_node_spec', jsonfield.fields.JSONField(help_text='registery node spec')),
                ('node_specs', jsonfield.fields.JSONField(help_text='node specs')),
                ('dt_updated', models.DateTimeField(help_text='更新时间')),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='registery',
            index=models.Index(fields=['registery_node'], name='rssant_api__registe_c3cb8e_idx'),
        ),
    ]
