# Generated by Django 2.2.6 on 2019-10-27 05:17

from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0012_auto_20191025_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('url_root', models.CharField(help_text='eg: https://image.example.com/root-path', max_length=120)),
                ('sample_url', models.CharField(blank=True, help_text='sample image url', max_length=240, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='the user-agent used to request sample image', max_length=240, null=True)),
                ('referer', models.CharField(blank=True, help_text='the referer used to request sample image', max_length=240, null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='the response status code when request sample image', null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='created datatime')),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='imageinfo',
            index=models.Index(fields=['url_root', 'dt_created'], name='rssant_api__url_roo_0d7c51_idx'),
        ),
    ]
