# Generated by Django 2.2.6 on 2019-10-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0013_auto_20191027_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='referer',
            field=models.TextField(blank=True, help_text='the referer used to request sample image', null=True),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='sample_url',
            field=models.TextField(blank=True, help_text='sample image url', null=True),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='user_agent',
            field=models.TextField(blank=True, help_text='the user-agent used to request sample image', null=True),
        ),
    ]
