# Generated by Django 2.2.6 on 2019-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0015_story_has_mathjax'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='dryness',
            field=models.IntegerField(blank=True, default=0, help_text='Dryness of the feed', null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='dt_first_story_published',
            field=models.DateTimeField(blank=True, help_text='最老的story发布时间', null=True),
        ),
    ]
