# Generated by Django 2.2.6 on 2019-12-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0016_auto_20191105_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='retention_offset',
            field=models.IntegerField(blank=True, default=0, help_text='stale story == offset < retention_offset', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='is_user_marked',
            field=models.BooleanField(blank=True, default=False, help_text='is user favorited or watched ever', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='has_mathjax',
            field=models.BooleanField(blank=True, default=False, help_text='has MathJax', null=True),
        ),
    ]
