# Generated by Django 2.2.10 on 2020-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0017_auto_20191217_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='freeze_level',
            field=models.IntegerField(blank=True, default=1, help_text='freeze level, 1: normal, N: slow down N times', null=True),
        ),
    ]
