# Generated by Django 2.2.12 on 2020-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0018_feed_freeze_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='use_proxy',
            field=models.BooleanField(blank=True, default=False, help_text='use proxy or not', null=True),
        ),
    ]
