# Generated by Django 2.2.12 on 2020-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0020_feed_checksum_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.TextField(blank=True, help_text='播客音频链接', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='iframe_url',
            field=models.TextField(blank=True, help_text='视频iframe链接', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.TextField(blank=True, help_text='图片链接', null=True),
        ),
    ]
