# Generated by Django 2.2.12 on 2020-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0022_feed_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='response_status',
            field=models.IntegerField(blank=True, help_text='response status code', null=True),
        ),
    ]
