# Generated by Django 2.2.12 on 2020-05-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0024_auto_20200510_1008'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='rssant_api__feed_id_1bed8a_idx',
        ),
    ]
