# Generated by Django 2.2.12 on 2020-05-23 14:00

from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0025_auto_20200516_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStoryStat',
            fields=[
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('id', models.PositiveIntegerField(help_text='feed id', primary_key=True, serialize=False)),
                ('monthly_story_count_data', models.BinaryField(blank=True, help_text='monthly story count data', max_length=514, null=True)),
                ('checksum_data', models.BinaryField(blank=True, help_text='feed checksum data', max_length=4096, null=True)),
                ('unique_ids_data', models.BinaryField(blank=True, help_text='unique ids data', max_length=102400, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(ool.VersionedMixin, models.Model),
        ),
    ]
