# Generated by Django 2.2.12 on 2020-05-28 15:48

from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0026_feedstorystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryInfo',
            fields=[
                ('_version', ool.VersionField(default=0)),
                ('id', models.BigIntegerField(help_text='feed_id and offset', primary_key=True, serialize=False)),
                ('unique_id', models.CharField(help_text='Unique ID', max_length=200)),
                ('title', models.CharField(help_text='标题', max_length=200)),
                ('link', models.TextField(help_text='文章链接')),
                ('author', models.CharField(blank=True, help_text='作者', max_length=200, null=True)),
                ('image_url', models.TextField(blank=True, help_text='图片链接', null=True)),
                ('audio_url', models.TextField(blank=True, help_text='播客音频链接', null=True)),
                ('iframe_url', models.TextField(blank=True, help_text='视频iframe链接', null=True)),
                ('has_mathjax', models.BooleanField(blank=True, help_text='has MathJax', null=True)),
                ('is_user_marked', models.BooleanField(blank=True, help_text='is user favorited or watched ever', null=True)),
                ('dt_published', models.DateTimeField(help_text='发布时间')),
                ('dt_updated', models.DateTimeField(blank=True, help_text='更新时间', null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('dt_synced', models.DateTimeField(blank=True, help_text='最近一次同步时间', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='content length', null=True)),
                ('summary', models.TextField(blank=True, help_text='摘要或较短的内容', null=True)),
                ('content_hash_base64', models.CharField(blank=True, help_text='base64 hash value of content', max_length=200, null=True)),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
    ]
