# Generated by Django 2.2.12 on 2020-06-19 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0027_storyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyinfo',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
    ]
