# Generated by Django 2.2.13 on 2020-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0028_auto_20200619_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='group',
            field=models.CharField(blank=True, help_text='用户设置的分组', max_length=200, null=True),
        ),
    ]
