# Generated by Django 2.2.13 on 2020-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0029_userfeed_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyinfo',
            name='sentence_count',
            field=models.IntegerField(blank=True, help_text='sentence count', null=True),
        ),
    ]
