# Generated by Django 2.2.13 on 2020-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0030_storyinfo_sentence_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sentence_count',
            field=models.IntegerField(blank=True, help_text='sentence count', null=True),
        ),
    ]
