# Generated by Django 2.2.13 on 2020-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0031_story_sentence_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcreation',
            name='group',
            field=models.CharField(blank=True, help_text='用户设置的分组', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedcreation',
            name='title',
            field=models.CharField(blank=True, help_text='用户设置的标题', max_length=200, null=True),
        ),
    ]
