# Generated by Django 2.2.28 on 2024-01-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ool


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rssant_api', '0032_auto_20201227_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False, help_text='是否发布', null=True),
        ),
        migrations.CreateModel(
            name='UserPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('is_enable', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否启用')),
                ('root_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问地址')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('dt_updated', models.DateTimeField(blank=True, help_text='更新时间', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='userpublish',
            index=models.Index(fields=['user'], name='rssant_api__user_id_e670e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userpublish',
            index=models.Index(fields=['root_url'], name='rssant_api__root_ur_f357b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpublish',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
    ]
