# Generated by Django 2.2.28 on 2024-08-21 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0033_auto_20240306_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('key', models.CharField(max_length=255, verbose_name='唯一标识')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('api', models.CharField(max_length=255, verbose_name='任务API')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(max_length=1048576, verbose_name='任务数据')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('dt_expired', models.DateTimeField(help_text='过期时间')),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['key'], name='rssant_api__key_6212db_idx'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['dt_expired'], name='rssant_api__dt_expi_9f8c87_idx'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['priority', 'dt_created'], name='rssant_api__priorit_746cbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='workertask',
            constraint=models.UniqueConstraint(fields=('key',), name='unique_key'),
        ),
    ]
