# Generated by Django 2.2.28 on 2024-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0033_auto_20240128_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublish',
            name='is_all_public',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否全部公开'),
        ),
    ]
