# Generated by Django 2.2.28 on 2024-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssant_api', '0034_userpublish_is_all_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublish',
            name='website_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网站标题'),
        ),
    ]
