# Generated by Django 2.2.28 on 2024-08-28 06:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ool


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rssant_api', '0034_auto_20240821_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_version', ool.VersionField(default=0)),
                ('_created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('_updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('vip_balance', models.BigIntegerField(blank=True, null=True, verbose_name='会员余额')),
                ('vip_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='会员信息')),
                ('dt_vip_synced', models.DateTimeField(blank=True, help_text='会员信息同步时间', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='rssant_api__user_id_d19d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='userprofile_unique_user'),
        ),
    ]
